server.port: 8888

sql.contact.list: |
  SELECT
    c.contact_first_name AS first,
    c.contact_middle_name AS middle,
    c.contact_last_name AS last,
    p.number
  FROM
    phones AS p
  INNER JOIN
    contacts AS c ON c.id = p.contact_id
  WHERE
    p.type = 'home'

logging:
  level:
    org.hibernate.SQL: debug

---
spring.config.activate.on-profile: networked1, networked2

spring.datasource:
  driver-class-name: org.hsqldb.jdbc.JDBCDriver
  url: jdbc:hsqldb:hsql://localhost/contacts
  username: sa
  password:

spring.jpa:
  show-sql: true

---
spring.config.activate.on-profile: networked1
spring:
  jpa:
    hibernate.ddl-auto: create
